// flow-typed signature: 4c3bf785e8e16ab01192b89ec5beef84
// flow-typed version: <<STUB>>/eslint-plugin-no-empty-blocks_v0.0.2/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-no-empty-blocks'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-no-empty-blocks' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-no-empty-blocks/lib/rules/no-empty-blocks' {
  declare module.exports: any;
}

declare module 'eslint-plugin-no-empty-blocks/test/lib/rules/no-empty-blocks' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-no-empty-blocks/index' {
  declare module.exports: $Exports<'eslint-plugin-no-empty-blocks'>;
}
declare module 'eslint-plugin-no-empty-blocks/index.js' {
  declare module.exports: $Exports<'eslint-plugin-no-empty-blocks'>;
}
declare module 'eslint-plugin-no-empty-blocks/lib/rules/no-empty-blocks.js' {
  declare module.exports: $Exports<'eslint-plugin-no-empty-blocks/lib/rules/no-empty-blocks'>;
}
declare module 'eslint-plugin-no-empty-blocks/test/lib/rules/no-empty-blocks.js' {
  declare module.exports: $Exports<'eslint-plugin-no-empty-blocks/test/lib/rules/no-empty-blocks'>;
}
