// flow-typed signature: 33bb58b6299ed98b64c5006d7752d605
// flow-typed version: <<STUB>>/eslint-plugin-no-use-extend-native_v^0.3.3/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-no-use-extend-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-no-use-extend-native' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-no-use-extend-native/rules/no-use-extend-native' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-no-use-extend-native/index' {
  declare module.exports: $Exports<'eslint-plugin-no-use-extend-native'>;
}
declare module 'eslint-plugin-no-use-extend-native/index.js' {
  declare module.exports: $Exports<'eslint-plugin-no-use-extend-native'>;
}
declare module 'eslint-plugin-no-use-extend-native/rules/no-use-extend-native.js' {
  declare module.exports: $Exports<'eslint-plugin-no-use-extend-native/rules/no-use-extend-native'>;
}
