// flow-typed signature: 9d09593f435e26ca066e339ab0785aaa
// flow-typed version: <<STUB>>/react-native-dismiss-keyboard_v1.0.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-dismiss-keyboard'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-dismiss-keyboard' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-dismiss-keyboard/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-dismiss-keyboard/dist/index.js' {
  declare module.exports: $Exports<'react-native-dismiss-keyboard/dist/index'>;
}
